urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from .views import first_page_view

urlpatterns = patterns('',

    # First page (Login)
    (r'^$', first_page_view),

    # App (API)
    (r'^app/', include('tnetwork.apps.api.urls')),
)

apps/api/daymatch/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.conf import settings
from django.utils import timezone

# --- Schedule ----------
class Schedule(models.Model):
    description = models.CharField(max_length=5)

    def __unicode__(self):
        return self.description

# --- Playgroup ----------
class Playgroup(models.Model):
    name = models.CharField(max_length=20)
    is_active = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

# --- Daymatch ------------
class Daymatch(models.Model):
    date = models.DateField()
    week = models.SmallIntegerField(null=True, blank=True)
    validated = models.BooleanField(default=0, verbose_name="Validation")

    class Meta:
        app_label = 'daymatch'
        ordering = ['-date']

    def save_first(self):
        self.week = self.date.isocalendar()[1]
        super(Daymatch, self).save()

    def save(self):
        super(Daymatch, self).save()

    def __unicode__(self):
        return "%s/%s/%s" % (self.date.day, self.date.month, self.date.year)

    def validate(self):
        self.validated = True
        self.save(update_fields=['validated'])
        return True

# --- DaymatchProg ------------
class DaymatchProg(models.Model):
    f_daymatch = models.ForeignKey(Daymatch)
    f_schedule = models.ForeignKey(Schedule)
    f_player = models.ForeignKey(settings.AUTH_USER_MODEL)

    def save(self):
        super(DaymatchProg, self).save()

    def __unicode__(self):
        return "%s (%s) : %s" % (self.f_daymatch, self.f_schedule, self.f_player)

apps/api/discus/models.py
# -*- coding: utf-8 -*-

"""
This module contains Discus models which allows to manage conversation 
on the tnetwork platform.
"""

from django.db import models
from django.conf import settings
from django.utils import timezone
import markdown
import simplejson as json

# --- Discus ------------
class Discus(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    f_daymatch = models.ForeignKey('daymatch.Daymatch')
    created_date = models.DateTimeField(auto_now_add=True, default=timezone.now)
    modified_date = models.DateTimeField(auto_now=True)
    body = models.TextField(max_length=140, verbose_name='discus_body')
    has_sons = models.BooleanField(verbose_name=u'has_sons', default=False)

    class Meta:
        ordering = ('created_date',)
        get_latest_by = 'created_date'

    def __unicode__(self):
        return self.body

    def delete(self):
        if self.has_sons:
            # Deleting all sons for this discus
            DiscusSon.objects.filter(f_discus=self).delete()
        super(Discus, self).delete()

    def get_all_sons(self):
        """
        Return a list of validated DiscusSons for which self is a parent. If self has not sons, return None.
        """
        if self.has_sons:
            return DiscusSon.objects.filter(f_discus=self)
        else:
            None

    def get_json(self):
        """
        Return a JSON string representation of self containing only id, created_date, author, body fields and a list of sons if self has sons.
        """
        data = {}

        data['id'] = self.id
        data['created_date'] = self.created_date.strftime("%Y-%m-%d")
        data['author'] = self.author.get_middle_name()
        data['body'] = self.body

        # Check if self has sons and get DiscusSon data
        sons = []
        if self.has_sons:
            for ds in DiscusSon.objects.filter(f_discus=self):
                sons.append(ds.get_json())
        data['sons'] = sons

        # Return a JSON string representation of data
        return json.dumps(data)

# --- DiscusSon ------------
class DiscusSon(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    f_discus = models.ForeignKey(Discus)
    created_date = models.DateTimeField(auto_now_add=True, default=timezone.now)
    modified_date = models.DateTimeField(auto_now=True)
    body = models.TextField(blank=True, null=True, verbose_name='discus_sons_body')

    class Meta:
        ordering = ('created_date',)
        get_latest_by = 'created_date'

    def __unicode__(self):
        return self.body

    def get_json(self):
        """
        Return a JSON string representation of self containing only id, created_date, author and body fields.
        """
        data = {}

        data['id'] = self.id
        data['created_date'] = self.created_date.strftime("%Y-%m-%d")
        data['author'] = self.author.get_middle_name()
        data['body'] = self.body

        # Return a JSON string representation of data
        return json.dumps(data)

apps/api/tnetworker/models.py
# -*- coding: utf-8 -*-

"""
These classes extend respectively BaseUserManager and AbstractBaseUser
abstract classes to define a custom User model compared to the Django
default User model. This capability is new from Django 1.5.
"""

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from tnetwork.libs.utils import generate_token
from api.daymatch.models import (Schedule, Playgroup)

class TNetworkerManager(BaseUserManager):
    def create_user(self, username, first_name, last_name, email, password):
        """
        Creates and saves a User with the given username, first_name, last_name, email and password. All these parameters are required.
        """
        if not username:
            raise ValueError('Users must have a username')
        if not first_name:
            raise ValueError('Users must have a first name')
        if not last_name:
            raise ValueError('Users must have a last name')
        if not email:
            raise ValueError('Users must have an email address')
        if not password:
            raise ValueError('Users must have a password')

        now = timezone.now()
        mail = TNetworkerManager.normalize_email(email)
        user = self.model(username=username, first_name=first_name, last_name=last_name, email=email, is_staff=False, is_active=True, is_superuser=False, last_login=now, date_joined=now, token=generate_token(username))
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, username, first_name, last_name, email, password):
        super_user = self.create_user(username, first_name, last_name, email, password)
        super_user.is_staff = True
        super_user.is_superuser = True
        super_user.save(using=self._db)
        return super_user

    def create_staff(self, username, first_name, last_name, email, password):
        staff = self.create_user(username, first_name, last_name, email, password)
        staff.is_staff = True
        staff.save(using=self._db)
        return staff


class TNetworker(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(verbose_name='email_address', max_length=255, unique=True, db_index=True)
    gsm = models.CharField(max_length=13, null=True, blank=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    registration_date = models.DateTimeField(blank=True, null=True)
    token = models.CharField(max_length=64, blank=True, null=True)

    # Custom parameters
    f_playgroup = models.ForeignKey(Playgroup, blank=True, null=True)
    f_schedule = models.ForeignKey(Schedule, blank=True, null=True)
    internal_counter = models.SmallIntegerField(default=0)

    objects = TNetworkerManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:
        verbose_name = u'tnetworker'
        verbose_name_plural = u'tnetworkers'

    def __unicode__(self):
        return self.email

    def get_full_name(self):
        """
        Returns the first_name (capitalized) plus the last_name (Uppercased), with a space in between.
        """
        return "%s %s" % ((self.first_name).capitalize(), (self.last_name).upper())

    def get_middle_name(self):
        """
        Returns the first_name (capitalized) plus the last_name (Uppercased), with a space in between.
        """
        return "%s. %s" % ((self.first_name[:1]).upper(), (self.last_name).upper())

    def get_short_name(self):
        """Returns the short name for the user."""
        return self.first_name

    def is_admin(self):
        return self.is_staff

    def disable_account(self):
        """
        Set the is_active tasker attribute to False.
        """
        # Set user as inactive
        self.is_active = False
        self.save(update_fields=['is_active'])
        return True

apps/api/discus/views.py
# Create your views here.

templates/old/partial/calendar.html
{% load api_plus %}
<div class="calendar">
  <ul class="unstyled">
    <!-- Item year -->
    {% for year, months in cal.items %}
    <li class="cal-year">
      <span><strong>{{ year }}</strong></span>

      <!-- Item daymatch lister -->
      {% for month, days in months.items %}
      <li class="cal-month">
        <div class="pull-left cal-month-title">
          <a href="{% if level == 'admin' %}/admin/match/{% else %}/calendar/{% endif %}{{ year }}/{{ month }}/">
            <span><strong>{{ month|str_month }}</strong></span>
          </a>
        </div>
        <ul class="unstyled cal-month-list">
          {% for day in days %}
          <li class="cal-day" data-date="{{ year }}/{{ month }}/{{ day }}">
            <a href="{% if level == 'admin' %}/admin/match/{% else %}/calendar/{% endif %}{{ year }}/{{ month }}/{{ day }}/">
              <span><strong>{{ day }}</strong></span>
            </a>
          </li>
          {% endfor %}
        </ul>
      </li>
      {% endfor %}
    </li>
    {% endfor %}
  </ul>
</div>

templates/old/partial/discus.html
{% load media %}
<ul class="unstyled post-container-list">
  {% for d in discus %}
  <li class="post-container" data-id="{{ d.0.id }}">
    <div class="discus-wrapper">
      {% autoescape on %}
      <div class="discus-infos">
        <img src="{% media_url 'img/global/ball_single.png' %}" class="pull-left avatar avatar32">
        <span class="tn"><strong>{{ d.0.author|capfirst }}</strong></span> posté il y a
        <time datetime="{{ d.0.created }}">{{ d.0.created|timesince }}</time>
      </div>
      <div class="discus-content">
        {{ d.0.body|safe }}
      </div>
      <ul class="unstyled son-container-list">
        {% if d.1 %}
          {% for son in d.1 %}
          <li class="son-container">
            <div class="son-wrapper">
              <div class="son-infos">
                <img src="{% media_url 'img/global/ball_single.png' %}" class="pull-left avatar avatar32">
                <span class="tn"><strong>{{ son.author|capfirst }}</strong></span> posté il y a
                <time datetime="{{ created.created }}">{{ son.created|timesince }}</time>
              </div>
              <div class="son-content">
                {{ son.body|safe }}
              </div>
            </div><!-- /end son-wrapper -->
          </li>
          {% endfor %}
        {% endif %}
      </ul>
      {% if button %}
      <div class="son-action">
        <a class="btn btn-inverse btn-mini add-son">Commenter</a>
      </div>
      {% endif %}
    {% endautoescape %}
    </div><!-- /end discus-wrapper -->
  </li>
  {% endfor %}
</ul>

templates/old/partial/player_edit.html
<form method="POST" action="#" id="player-action">
  {% csrf_token %}
  <fieldset>
    <dl>
      <dd class="pull-right">{{ form.name }}</dd>
      <dt>
        <label for="id_name"><strong>Nom</strong><span class="red-tn">*</span></label>
      </dt>
    </dl>
    <dl>
      <dd class="pull-right">{{ form.fname }}</dd>
      <dt>
        <label for="id_fname"><strong>Prénom</strong><span class="red-tn">*</span></label>
      </dt>
    </dl>
    <dl>
      <dd class="pull-right">{{ form.mail }}</dd>
      <dt>
        <label for="id_mail"><strong>Email</strong><span class="red-tn">*</span></label>
      </dt>
    </dl>
    <dl>
      <dd class="pull-right">{{ form.gsm }}</dd>
      <dt>
        <label for="id_gsm"><strong>GSM</strong></label>
      </dt>
    </dl>
    <dl>
      <dd class="pull-right">{{ form.half_time }}</dd>
      <dt>
        <label for="id_ht"><strong>Temps</strong><span class="red-tn">*</span></label>
      </dt>
    </dl>
    <dl>
      <dd class="pull-right">{{ form.time_pref }}</dd>
      <dt>
        <label for="id_time"><strong>Horaire</strong><span class="red-tn">*</span></label>
      </dt>
    </dl>
  </fieldset>
</form>